<?php

namespace AppBundle\Repository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends \Doctrine\ORM\EntityRepository
{

	public function findNextEpisodesOrderByDate()
	{
		$query = $this
        	->createQueryBuilder('e')
        	->where('DATE_DIFF(CURRENT_DATE(), e.date) <= 0')
    		->orderBy('e.date', 'ASC')
        	->getQuery();

        return $query->getResult();
	}

}